version: '3.4'

x-common-variables: &common-variables
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: master

services:
  database:
    image: postgres:11.2
    restart: always
    environment: *common-variables
    ports:
    - "5432"

  web:
    build: .
    command: python /home/worker/app.py
    volumes:
      - ./web:/home/worker
    ports:
      - "5000:5000"
    depends_on:
      - database
      - api
    restart: always

  api:
    build: .
    command: python /home/worker/app.py
    volumes:
      - ./api:/home/worker
    ports:
      - "5050:5050"
    depends_on:
      - database
      - worker
    environment: *common-variables
    restart: always

  worker:
    build: .
    command: python worker.py
    volumes:
      - ./worker:/home/worker
      - ./utils:/home/worker/utils
    depends_on:
      - database
    environment: *common-variables
    restart: always
