version: '3'

services:
  database:
    image: postgres:11.2
    restart: always
    ports:
    - "5432"

  web:
    build: .
    command: python /home/worker/app.py
    volumes:
      - ./web:/home/worker
    ports:
      - "5000:5000"
    depends_on:
      - database
      - api
    restart: always

  api:
    build: .
    command: python /home/worker/app.py
    volumes:
      - ./api:/home/worker
    ports:
      - "5050:5050"
    depends_on:
      - database
    restart: always

  worker:
    build: .
    command: python /home/worker/worker.py
    volumes:
      - ./worker:/home/worker
    depends_on:
      - database
    restart: always
