version: '3.7'

x-common-variables: &common-variables
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: master
  POSTGRES_HOST: database

services:
  database:
    image: postgres:11.2
    restart: always
    environment: *common-variables
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn -w 3 -k gevent -b 0.0.0.0:5000 app:app
    environment: 
      <<: *common-variables
      STOCKS_USERNAME: hello
      STOCKS_PASSWORD: yoyo
      SESSION_SECRET: '897f35f8d104e4a9e4a67f8d757b0dbd4028f85aed24c721ee4d79e618cc9560'
    volumes:
      - ./web:/home/worker
      - ./utils:/home/worker/utils
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: always

  worker:
    build: .
    command: ./worker_entrypoint.sh
    volumes:
      - ./worker:/home/worker
      - ./utils:/home/worker/utils
      - ./tests:/home/worker/tests
    depends_on:
      - database
    environment: *common-variables
    restart: always
