version: '3.7'

x-common-variables: &common-variables
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: master
  POSTGRES_HOST: database

services:
  database:
    image: postgres:11.2
    restart: always
    environment: *common-variables
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: python /home/worker/app.py
    volumes:
      - ./web:/home/worker
    ports:
      - "5000:5000"
    depends_on:
      - database
      - api
    restart: always

  api:
    build: .
    command: gunicorn -b 0.0.0.0:5050 app:app
    volumes:
      - ./api:/home/worker
      - ./utils:/home/worker/utils
    ports:
      - "5050:5050"
    depends_on:
      - database
      - worker
    environment: *common-variables
    restart: always

  worker:
    build: .
    command: ./worker_entrypoint.sh
    volumes:
      - ./worker:/home/worker
      - ./utils:/home/worker/utils
      - ./tests:/home/worker/tests
    depends_on:
      - database
    environment: *common-variables
    restart: always
